# Generated by Django 6.1.1 on 2026-09-14 22:50

import django.contrib.postgres.indexes
import django.contrib.postgres.search
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="search_vector",
            field=django.contrib.postgres.search.SearchVectorField(
                editable=False, null=True
            ),
        ),
        migrations.AddField(
            model_name="thesis",
            name="tags_text",
            field=models.TextField(blank=True, default=""),
        ),
        migrations.AddIndex(
            model_name="thesis",
            index=django.contrib.postgres.indexes.GinIndex(
                fields=["search_vector"], name="thesis_search_gin"
            ),
        ),
    ]
