# Generated by Django 6.1.1 on 2026-09-16 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0005_alter_thesis_file"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="downloads",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
