# Generated by Django 6.1.1 on 2026-09-14 21:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=60, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Thesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=300)),
                ("author", models.CharField(max_length=150)),
                ("department", models.CharField(blank=True, max_length=150)),
                ("faculty", models.CharField(blank=True, max_length=150)),
                ("year", models.PositiveIntegerField(blank=True, null=True)),
                ("abstract", models.TextField(blank=True)),
                ("supervisor", models.CharField(blank=True, max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("draft", "Draft"),
                            ("processing", "Processing"),
                            ("published", "Published"),
                            ("flagged", "Flagged"),
                        ],
                        default="draft",
                        max_length=20,
                    ),
                ),
                (
                    "access_policy",
                    models.CharField(
                        choices=[
                            ("public", "Public"),
                            ("restricted", "Restricted"),
                            ("private", "Private"),
                        ],
                        default="public",
                        max_length=20,
                    ),
                ),
                ("file", models.FileField(blank=True, null=True, upload_to="theses/")),
                (
                    "processing_status",
                    models.CharField(
                        choices=[
                            ("none", "Not processed"),
                            ("queued", "Queued"),
                            ("processing", "Processing"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                        ],
                        default="none",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="theses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "tags",
                    models.ManyToManyField(
                        blank=True, related_name="theses", to="theses.tag"
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
            },
        ),
        migrations.CreateModel(
            name="SavedThesis",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_theses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="saved_by",
                        to="theses.thesis",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AccessRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("message", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("denied", "Denied"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "requester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="access_requests",
                        to="theses.thesis",
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="thesis",
            index=models.Index(fields=["status"], name="theses_thes_status_b3859a_idx"),
        ),
        migrations.AddIndex(
            model_name="thesis",
            index=models.Index(
                fields=["department"], name="theses_thes_departm_3713cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thesis",
            index=models.Index(
                fields=["faculty"], name="theses_thes_faculty_6d8872_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="thesis",
            index=models.Index(fields=["year"], name="theses_thes_year_03e6e3_idx"),
        ),
        migrations.AlterUniqueTogether(
            name="savedthesis",
            unique_together={("user", "thesis")},
        ),
        migrations.AlterUniqueTogether(
            name="accessrequest",
            unique_together={("thesis", "requester")},
        ),
    ]
