# Generated by Django 6.1.1 on 2026-09-14 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0002_thesis_search_vector_thesis_tags_text_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="thesis",
            name="views",
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
    ]
