# Generated by Django 6.1.1 on 2026-09-14 23:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theses", "0004_backfill_search_vectors"),
    ]

    operations = [
        migrations.AlterField(
            model_name="thesis",
            name="file",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="theses/",
                validators=[django.core.validators.FileExtensionValidator(["pdf"])],
            ),
        ),
    ]
