# Generated by Django 6.1.1 on 2026-09-14 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ResearcherProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bio", models.TextField(blank=True)),
                (
                    "orcid",
                    models.URLField(
                        blank=True, help_text="https://orcid.org/XXXX-XXXX-XXXX-XXXX"
                    ),
                ),
                (
                    "github",
                    models.CharField(
                        blank=True, help_text="GitHub username", max_length=80
                    ),
                ),
                ("website", models.URLField(blank=True)),
                ("research_interests", models.TextField(blank=True)),
                ("is_available_for_mentoring", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="researcher_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
