# Generated by Django 6.1.1 on 2026-09-16 09:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("theses", "0005_alter_thesis_file"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=100)),
                (
                    "subject_type",
                    models.CharField(blank=True, default="", max_length=100),
                ),
                ("subject_id", models.PositiveIntegerField(blank=True, null=True)),
                ("detail", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_events",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["action"], name="admin_panel_action_690ed1_idx"
                    ),
                    models.Index(
                        fields=["subject_type", "subject_id"],
                        name="admin_panel_subject_a51400_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="ModerationItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "flag_type",
                    models.CharField(
                        choices=[
                            ("high_similarity", "High similarity"),
                            ("standard_review", "Standard review"),
                            ("metadata", "Metadata"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "similarity_score",
                    models.FloatField(
                        blank=True,
                        help_text="AI similarity score (optional).",
                        null=True,
                    ),
                ),
                ("note", models.TextField(blank=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("approved", "Approved"),
                            ("dismissed", "Dismissed"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("reviewed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "reporter",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_reports",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reviewer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="moderation_reviews",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "thesis",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="moderation_items",
                        to="theses.thesis",
                    ),
                ),
            ],
            options={
                "ordering": ("-created_at",),
                "indexes": [
                    models.Index(
                        fields=["status"], name="admin_panel_status_51a605_idx"
                    ),
                    models.Index(
                        fields=["flag_type"], name="admin_panel_flag_ty_3cb878_idx"
                    ),
                ],
            },
        ),
    ]
