import React from 'react';
import { Activity, AlertTriangle, ArrowUpRight, BarChart2, CheckCircle, Clock3, FileText, ShieldCheck, TrendingUp, Users } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, BarChart, Bar } from 'recharts';
import { useAppRouter, AuthenticatedLayout, Card, Badge, Button } from '../components/shared';

const trend = [{name:'Jan',uploads:180},{name:'Feb',uploads:230},{name:'Mar',uploads:270},{name:'Apr',uploads:340},{name:'May',uploads:390},{name:'Jun',uploads:460}];
const activity = [
  ['10:02 AM','New thesis uploaded','Machine Learning for Crop Yield Prediction','Review queue'],
  ['09:45 AM','AI similarity flag','Analysis of Soil pH using Sensor Networks','Needs review'],
  ['08:30 AM','Faculty verified','Dr. Tunde Adeyemi','Completed'],
  ['08:12 AM','Thesis published','Yoruba Proverbs Database','Completed'],
];

const Screen43AdminDashboard = () => {
  const { navigate } = useAppRouter();
  return <AuthenticatedLayout title="Admin Dashboard" admin><div className="max-w-7xl mx-auto space-y-6">
    <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-4"><div><Badge variant="green">System operations</Badge><h2 className="mt-2 text-2xl sm:text-3xl font-bold tracking-tight">Good morning, Administrator.</h2><p className="mt-1 text-sm text-slate-500">A quick view of repository health, moderation and research activity.</p></div><div className="flex gap-2"><Button variant="secondary" onClick={() => navigate('content-moderation')}>Review queue <ArrowUpRight className="ml-2 h-4 w-4"/></Button><Button onClick={() => navigate('user-management')}>Manage users</Button></div></div>
    <div className="grid grid-cols-1 sm:grid-cols-2 xl:grid-cols-4 gap-4">{[
      {icon:FileText,label:'Total theses',value:'12,450',sub:'+8.2% this year'}, {icon:Users,label:'Active users',value:'8,201',sub:'+4.7% this month'}, {icon:Clock3,label:'Pending review',value:'45',sub:'12 flagged by AI'}, {icon:ShieldCheck,label:'System health',value:'99.9%',sub:'All services operational'}
    ].map((s,i)=>{const I=s.icon;return <Card key={s.label} className="p-5"><div className="flex justify-between"><span className="h-9 w-9 rounded-lg bg-emerald-50 text-[#00502F] flex items-center justify-center"><I className="h-4 w-4"/></span>{i<2?<TrendingUp className="h-4 w-4 text-emerald-600"/>:<Activity className="h-4 w-4 text-slate-400"/>}</div><p className="mt-5 text-2xl font-bold">{s.value}</p><p className="mt-1 text-xs font-medium text-slate-700">{s.label}</p><p className="mt-1 text-[11px] text-slate-500">{s.sub}</p></Card>})}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[1.55fr_1fr] gap-6"><Card className="p-5 sm:p-6"><div className="flex justify-between items-start"><div><h3 className="font-bold">Repository activity</h3><p className="text-xs text-slate-500 mt-1">New submissions over the last six months</p></div><BarChart2 className="h-5 w-5 text-slate-400"/></div><div className="h-72 mt-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="adminFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00502F" stopOpacity={0.18}/><stop offset="100%" stopColor="#00502F" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:'#64748B',fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#64748B',fontSize:12}}/><Tooltip/><Area type="monotone" dataKey="uploads" stroke="#00502F" strokeWidth={2.5} fill="url(#adminFill)"/></AreaChart></ResponsiveContainer></div></Card>
    <Card className="p-5 sm:p-6"><div className="flex items-center justify-between"><div><h3 className="font-bold">Moderation queue</h3><p className="text-xs text-slate-500 mt-1">Items requiring attention</p></div><AlertTriangle className="h-5 w-5 text-amber-500"/></div><div className="mt-5 space-y-3">{[['High priority','12','AI similarity flags'],['Standard review','33','Metadata checks'],['Access requests','18','Waiting for approval']].map(x=><button key={x[0]} onClick={()=>navigate('content-moderation')} className="w-full text-left rounded-xl border border-slate-200 p-4 hover:bg-slate-50 transition"><div className="flex justify-between"><span className="text-sm font-semibold">{x[0]}</span><span className="font-bold text-[#00502F]">{x[1]}</span></div><p className="text-xs text-slate-500 mt-1">{x[2]}</p></button>)}</div></Card></div>
    <Card className="overflow-hidden"><div className="px-5 py-4 border-b border-slate-200 flex items-center justify-between"><div><h3 className="font-bold">Recent system activity</h3><p className="text-xs text-slate-500 mt-1">Latest repository events</p></div><Button variant="ghost" size="sm">View all <ArrowUpRight className="ml-1 h-3.5 w-3.5"/></Button></div><div className="divide-y divide-slate-100">{activity.map(([time,title,subject,status])=><div key={time+title} className="p-4 sm:px-5 flex items-start gap-3"><span className={`mt-1 h-8 w-8 rounded-lg flex items-center justify-center ${status==='Needs review'?'bg-amber-50 text-amber-600':'bg-emerald-50 text-emerald-700'}`}>{status==='Needs review'?<AlertTriangle className="h-4 w-4"/>:<CheckCircle className="h-4 w-4"/>}</span><div className="flex-1 min-w-0"><div className="flex flex-col sm:flex-row sm:justify-between gap-1"><p className="text-sm font-semibold text-slate-800">{title}</p><span className="text-[11px] text-slate-400">{time}</span></div><p className="text-xs text-slate-500 mt-1 truncate">{subject}</p></div><Badge variant={status==='Needs review'?'gold':'green'}>{status}</Badge></div>)}</div></Card>
  </div></AuthenticatedLayout>;
};
export default Screen43AdminDashboard;
