import React, { useState, useEffect, useContext, createContext } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import {
  Search, BookOpen, Users, Cpu, FileText, ChevronRight, Lock, Unlock, Mail, Settings,
  LogOut, Bell, MessageSquare, Activity, BarChart2, PlusCircle, CheckCircle, AlertTriangle,
  Download, Bookmark, Share2, Filter, MoreVertical, X, Menu, Home, Grid, Lightbulb,
  FileSearch, UserPlus, Shield, Check, FileUp, Database, GitBranch, ArrowRight, ArrowLeft,
  MessageCircle, Link as LinkIcon, ThumbsUp, Send, PieChart, TrendingUp, Search as SearchIcon,
  ShieldAlert, Settings2, Sliders, ChevronDown, Book, User, Calendar
} from 'lucide-react';
import {
  LineChart, Line, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer,
  BarChart, Bar, PieChart as RePieChart, Pie, Cell, AreaChart, Area
} from 'recharts';
import {
  theme, MOCK_THESES, MOCK_USERS, MOCK_MESSAGES, useAppRouter,
  Button, Input, Card, Badge, PublicLayout, AuthenticatedLayout, AuthContainer,
  ThesisCard, UploadWizardNav, pageVariants, listVariants, itemVariants
} from '../components/shared';

const Screen10ThesisAI = () => {
  const { navigate } = useAppRouter();
  return (
    <AuthenticatedLayout title="AI Document Summary">
      <div className="max-w-4xl mx-auto">
        <div className="flex items-center space-x-2 mb-8 cursor-pointer text-slate-500 hover:text-slate-800" onClick={() => navigate('thesis-detail')}>
          <ArrowLeft className="w-4 h-4" /> <span>Back to Thesis</span>
        </div>
        
        <div className="bg-white rounded-xl shadow-sm border border-slate-200 overflow-hidden">
          <div className="bg-emerald-50 p-6 border-b border-emerald-100 flex items-start space-x-4">
            <div className="p-2 bg-emerald-100 rounded-lg text-emerald-600"><Cpu className="w-6 h-6"/></div>
            <div>
              <h2 className="text-lg font-semibold text-emerald-900">AI-Generated Analysis</h2>
              <p className="text-sm text-emerald-700 mt-1">This summary is generated by OAU Thesis AI. It highlights key structural components of the research document.</p>
            </div>
          </div>
          
          <div className="p-8 space-y-8">
            <section>
              <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-3">Core Problem Addressed</h3>
              <p className="text-slate-800 text-lg">Inaccurate prediction of crop yields due to reliance on traditional meteorological forecasting rather than localized, data-driven machine learning models.</p>
            </section>
            
            <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
              <section className="bg-slate-50 p-5 rounded-lg border border-slate-100">
                <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-3">Methodology Snapshot</h3>
                <ul className="space-y-2 text-sm text-slate-700">
                  <li className="flex items-start"><span className="text-[#D4AF37] mr-2">•</span> Random Forest Regressor algorithm.</li>
                  <li className="flex items-start"><span className="text-[#D4AF37] mr-2">•</span> 10-year localized weather dataset (NIMET).</li>
                  <li className="flex items-start"><span className="text-[#D4AF37] mr-2">•</span> 80/20 train-test split cross-validation.</li>
                </ul>
              </section>
              
              <section className="bg-slate-50 p-5 rounded-lg border border-slate-100">
                <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-3">Key Findings</h3>
                <p className="text-sm text-slate-700 mb-2">The model achieved an R² score of 0.89, outperforming baseline models by 15%.</p>
                <p className="text-sm text-slate-700">Soil moisture was identified as the single highest weighted feature for prediction accuracy.</p>
              </section>
            </div>
            
            <section className="border-t border-slate-200 pt-6">
              <h3 className="text-sm font-bold uppercase tracking-wider text-slate-500 mb-3 flex items-center"><AlertTriangle className="w-4 h-4 mr-2 text-amber-500"/> Noted Limitations</h3>
              <p className="text-slate-700">The study explicitly notes that the dataset is restricted to Osun State, meaning the model may not generalize well to northern Nigerian climates without retraining.</p>
              <Button variant="ghost" className="mt-4 text-[#00502F]" onClick={() => navigate('gap-detail')}>Explore this as a Research Gap <ArrowRight className="w-4 h-4 ml-1"/></Button>
            </section>
          </div>
        </div>
      </div>
    </AuthenticatedLayout>
  );
};

export default Screen10ThesisAI;
