import React from 'react';
import { ArrowUpRight, BarChart2, BookOpen, Building2, Download, GraduationCap, TrendingUp, Users } from 'lucide-react';
import { BarChart, Bar, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer, PieChart, Pie, Cell, AreaChart, Area } from 'recharts';
import { useAppRouter, AuthenticatedLayout, Card, Badge, Button } from '../components/shared';

const faculties = [{name:'Science',value:3200},{name:'Technology',value:2780},{name:'Arts',value:1950},{name:'Agriculture',value:1620},{name:'Social Sciences',value:2910}];
const trend = [{year:'2021',projects:820},{year:'2022',projects:980},{year:'2023',projects:1240},{year:'2024',projects:1510},{year:'2025',projects:1780}];
const areas = [{name:'Artificial Intelligence',growth:145},{name:'Renewable Energy',growth:82},{name:'Digital Economy',growth:64},{name:'Climate Agriculture',growth:41}];
const pie = [{name:'Science',value:28},{name:'Technology',value:24},{name:'Social Sciences',value:21},{name:'Agriculture',value:14},{name:'Arts',value:13}];

const Screen40UniversityAnalytics = () => {
  const { navigate } = useAppRouter();
  return <AuthenticatedLayout title="University Research Analytics"><div className="max-w-7xl mx-auto space-y-6">
    <div className="rounded-2xl bg-[#00502F] p-6 sm:p-8 text-white relative overflow-hidden"><div className="absolute -right-12 -top-20 h-64 w-64 rounded-full border border-white/10"/><div className="relative flex flex-col lg:flex-row lg:items-end lg:justify-between gap-6"><div><Badge variant="gold">Institutional intelligence</Badge><h2 className="mt-3 text-2xl sm:text-3xl font-bold">OAU research, seen as a whole.</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-emerald-100">A university-level view of research output, emerging areas and repository engagement.</p></div><div className="grid grid-cols-2 gap-6"><div><p className="text-3xl font-bold text-[#D4AF37]">12,450</p><p className="text-[11px] uppercase tracking-wider text-emerald-100">Indexed projects</p></div><div><p className="text-3xl font-bold">3,912</p><p className="text-[11px] uppercase tracking-wider text-emerald-100">Researchers</p></div></div></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[{icon:BookOpen,value:'12,450',label:'Projects indexed'},{icon:Users,value:'3,912',label:'Research profiles'},{icon:TrendingUp,value:'+24%',label:'YoY output growth'},{icon:Building2,value:'40+',label:'Academic areas'}].map((s,i)=>{const I=s.icon;return <Card key={s.label} className="p-5"><I className={i===2?'h-4 w-4 text-[#D4AF37]':'h-4 w-4 text-[#00502F]'}/><p className="mt-4 text-2xl font-bold">{s.value}</p><p className="mt-1 text-xs text-slate-500">{s.label}</p></Card>})}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[1.4fr_1fr] gap-6"><Card className="p-5 sm:p-6"><div className="flex justify-between items-start"><div><h3 className="font-bold">Research output trend</h3><p className="text-xs text-slate-500 mt-1">Published projects by year</p></div><BarChart2 className="h-5 w-5 text-slate-400"/></div><div className="h-72 mt-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={trend}><defs><linearGradient id="uniFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00502F" stopOpacity={0.2}/><stop offset="100%" stopColor="#00502F" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0"/><XAxis dataKey="year" axisLine={false} tickLine={false} tick={{fill:'#64748B',fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#64748B',fontSize:12}}/><Tooltip/><Area type="monotone" dataKey="projects" stroke="#00502F" strokeWidth={2.5} fill="url(#uniFill)"/></AreaChart></ResponsiveContainer></div></Card>
    <Card className="p-5 sm:p-6"><h3 className="font-bold">Repository mix</h3><p className="text-xs text-slate-500 mt-1">Share of indexed projects</p><div className="h-56 mt-2"><ResponsiveContainer width="100%" height="100%"><PieChart><Pie data={pie} dataKey="value" nameKey="name" innerRadius={58} outerRadius={82} paddingAngle={3}>{pie.map((_,i)=><Cell key={i} fill={['#00502F','#D4AF37','#64748B','#10B981','#94A3B8'][i]}/>)}</Pie><Tooltip/></PieChart></ResponsiveContainer></div><div className="space-y-2">{pie.map((p,i)=><div key={p.name} className="flex items-center justify-between text-xs"><span className="flex items-center gap-2 text-slate-600"><span className="h-2 w-2 rounded-full" style={{background:['#00502F','#D4AF37','#64748B','#10B981','#94A3B8'][i]}}/>{p.name}</span><span className="font-semibold">{p.value}%</span></div>)}</div></Card></div>
    <div className="grid grid-cols-1 xl:grid-cols-2 gap-6"><Card className="p-5 sm:p-6"><div className="flex items-center justify-between mb-5"><div><h3 className="font-bold">Output by faculty group</h3><p className="text-xs text-slate-500 mt-1">Indexed research projects</p></div><GraduationCap className="h-5 w-5 text-[#D4AF37]"/></div><div className="h-72"><ResponsiveContainer width="100%" height="100%"><BarChart data={faculties}><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:'#64748B',fontSize:11}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#64748B',fontSize:11}}/><Tooltip/><Bar dataKey="value" fill="#00502F" radius={[5,5,0,0]}/></BarChart></ResponsiveContainer></div></Card><Card className="p-5 sm:p-6"><div className="flex items-center justify-between mb-5"><div><h3 className="font-bold">Fastest-growing research areas</h3><p className="text-xs text-slate-500 mt-1">Year-over-year change</p></div><TrendingUp className="h-5 w-5 text-[#D4AF37]"/></div><div className="space-y-3">{areas.map(a=><div key={a.name} className="rounded-xl border border-slate-200 p-4 flex items-center gap-4"><div className="flex-1"><p className="text-sm font-semibold">{a.name}</p><div className="mt-2 h-1.5 rounded-full bg-slate-100"><div className="h-full rounded-full bg-[#00502F]" style={{width:`${Math.min(a.growth/1.5,100)}%`}}/></div></div><Badge variant="green">+{a.growth}%</Badge></div>)}</div></Card></div>
    <div className="flex justify-end"><Button variant="secondary"><Download className="h-4 w-4 mr-2"/> Export institutional report</Button></div>
  </div></AuthenticatedLayout>;
};
export default Screen40UniversityAnalytics;
