import React from 'react';
import { ArrowLeft, Download, Eye, Bookmark, Quote, Share2, TrendingUp, Users } from 'lucide-react';
import { AreaChart, Area, XAxis, YAxis, CartesianGrid, Tooltip, ResponsiveContainer } from 'recharts';
import { useAppRouter, AuthenticatedLayout, Card, Badge, Button } from '../components/shared';

const data = [{name:'Jan', views:120}, {name:'Feb', views:180}, {name:'Mar', views:240}, {name:'Apr', views:360}, {name:'May', views:510}, {name:'Jun', views:620}];
const sources = [{label:'Semantic search', value:65}, {label:'Researcher profiles', value:25}, {label:'AI recommendations', value:10}];

const Screen39ThesisAnalytics = () => {
  const { navigate } = useAppRouter();
  return <AuthenticatedLayout title="Thesis Impact Analytics"><div className="max-w-7xl mx-auto space-y-6">
    <button onClick={() => navigate('my-projects')} className="inline-flex items-center gap-2 text-sm text-slate-500 hover:text-[#00502F]"><ArrowLeft className="h-4 w-4"/> Back to my projects</button>
    <div className="flex flex-col lg:flex-row lg:items-end lg:justify-between gap-5"><div><Badge variant="green">Published · 2023</Badge><h2 className="mt-3 text-2xl sm:text-3xl font-bold tracking-tight">Machine Learning for Crop Yield Prediction in Nigeria</h2><p className="mt-2 text-sm text-slate-500">Agricultural Engineering · Adekunle Ojo</p></div><div className="flex gap-2"><Button variant="secondary"><Share2 className="h-4 w-4 mr-2"/> Share</Button><Button><Download className="h-4 w-4 mr-2"/> Export report</Button></div></div>
    <div className="grid grid-cols-2 lg:grid-cols-4 gap-4">{[{icon:Eye,value:'890',label:'Document views'},{icon:Download,value:'214',label:'PDF downloads'},{icon:Bookmark,value:'45',label:'Saves'},{icon:Quote,value:'8',label:'Internal citations'}].map((s,i)=>{const Icon=s.icon; return <Card key={s.label} className="p-5"><Icon className={`h-4 w-4 ${i===3?'text-[#D4AF37]':'text-[#00502F]'}`}/><p className="mt-4 text-2xl font-bold">{s.value}</p><p className="mt-1 text-xs text-slate-500">{s.label}</p></Card>})}</div>
    <div className="grid grid-cols-1 xl:grid-cols-[1.6fr_1fr] gap-6"><Card className="p-5 sm:p-6"><h3 className="font-bold">Document views</h3><p className="text-xs text-slate-500 mt-1">Cumulative readership over the selected period</p><div className="h-72 mt-5"><ResponsiveContainer width="100%" height="100%"><AreaChart data={data}><defs><linearGradient id="impactFill" x1="0" y1="0" x2="0" y2="1"><stop offset="0%" stopColor="#00502F" stopOpacity={0.2}/><stop offset="100%" stopColor="#00502F" stopOpacity={0}/></linearGradient></defs><CartesianGrid strokeDasharray="3 3" vertical={false} stroke="#E2E8F0"/><XAxis dataKey="name" axisLine={false} tickLine={false} tick={{fill:'#64748B',fontSize:12}}/><YAxis axisLine={false} tickLine={false} tick={{fill:'#64748B',fontSize:12}}/><Tooltip/><Area type="monotone" dataKey="views" stroke="#00502F" strokeWidth={2.5} fill="url(#impactFill)"/></AreaChart></ResponsiveContainer></div></Card>
    <Card className="p-5 sm:p-6"><div className="flex items-center gap-2"><TrendingUp className="h-4 w-4 text-[#D4AF37]"/><h3 className="font-bold">How readers found it</h3></div><div className="mt-6 space-y-5">{sources.map(s=><div key={s.label}><div className="flex justify-between text-xs mb-2"><span className="text-slate-600">{s.label}</span><span className="font-bold">{s.value}%</span></div><div className="h-2 rounded-full bg-slate-100 overflow-hidden"><div className="h-full rounded-full bg-[#00502F]" style={{width:`${s.value}%`}}/></div></div>)}</div><div className="mt-8 pt-5 border-t border-slate-100 flex items-center gap-3"><span className="h-9 w-9 rounded-full bg-emerald-50 flex items-center justify-center"><Users className="h-4 w-4 text-[#00502F]"/></span><div><p className="text-sm font-semibold">214 unique readers</p><p className="text-xs text-slate-500">Across the OAU research network</p></div></div></Card></div>
    <Card className="p-5 sm:p-6"><h3 className="font-bold">Impact signals</h3><div className="mt-5 grid grid-cols-1 md:grid-cols-3 gap-4">{[['Research visibility','High','Your project appears frequently in related semantic searches.'],['Reader engagement','Growing','Downloads are increasing alongside document views.'],['Research reuse','8 citations','Other OAU projects have referenced this work.']].map(([a,b,c])=><div key={a} className="rounded-xl border border-slate-200 p-4"><p className="text-xs text-slate-500">{a}</p><p className="mt-2 font-bold text-[#00502F]">{b}</p><p className="mt-1 text-xs leading-5 text-slate-500">{c}</p></div>)}</div></Card>
  </div></AuthenticatedLayout>;
};
export default Screen39ThesisAnalytics;
